### PR TITLE
add rule for new style constructor name

### PR DESCRIPTION
**Pull request by raininja**
OK got it, here is the correct pull request :dancer: @duaraghav8

### CODE REVIEW

**Comment by duaraghav8** [comment]
@raininja Sorry for the delay in review. Please add tests for the `fix()` functionality, everything else is good.

**Comment by raininja** [comment]
@duaraghav8 ok, I'm having eye issues right now so I will try lol

**Comment by raininja** [comment]
@duaraghav8  complete

**Comment by duaraghav8** [comment]
combined and merged with #207

**Pull request closed without merging**
