### PR TITLE
Adds --fix-dry-run option

### LINKED ISSUE #170: add --fix-dry-run
The `--fix-dry-run` option is exactly what it sounds like - it simply prints a report about what all fixes solium is going to apply instead of actually writing over files. This gives the user a **diff** between current code & what it would look like after applying the fixes.

### PR DESCRIPTION
**Pull request by mushketyk**
Fixes #170

### CODE REVIEW

**Comment by mushketyk** [comment]
Here how the diff looks like in the console:

image

**Comment by mushketyk** [comment]
One issue though. At the moment diff will include all lines from a file. We can remove some unchanged lines like git does it, but I am not sure if it worth it. What do you think?

**Comment by duaraghav8** [comment]
This looks great @mushketyk 
Yes, it is absolutely worth compressing the unchanged lines just like git does.
I just ran your `dry-run` branch over [zeppelin contracts](https://github.com/OpenZeppelin/zeppelin-solidity). As you can see, with large codebases, this produces a lot of irrelevant lines that shouldn't concern the user.
Do you think you can achieve this (does the `diff` library have this feature in built)?


screen shot 2018-04-03 at 2 57 34 pm

**Comment by mushketyk** [comment]
@duaraghav8 Makes sense. I'll look into this. 

>Does the diff library have this feature in built
It has another methods called `createPatch`. Maybe it can generate a proper diff.

**Comment by mushketyk** [comment]
Hi @duaraghav8 I've updated the pull request and now diffs are much more readable:

image

**Comment by duaraghav8** [comment]
@mushketyk is there an easy way to also display the line numbers? something like:
```
Diff for: /Users/raghavdua/Desktop/github/zeppelin-solidity/contracts/token/ERC20/TokenVesting.sol
@@ -71,9 +71,9 @@
28     released[token] = released[token].add(unreleased);
29     token.safeTransfer(beneficiary, unreleased);
30
31 -    Released(unreleased);
31 +    emit Released(unreleased);
32   }
```

Note: if there is no easy way to implement this, then we'll leave it for now and make modifications in subsequent iterations

**Comment by mushketyk** [comment]
Hi @duaraghav8,

Sorry for a late response.

That won't be that straightforward, unfortunately. We can get a raw diff from this library then count and display line numbers. None of this is provided out of the box.

**Comment by duaraghav8** [comment]
@mushketyk not a problem!

**Pull request merged**
