### PR TITLE
operator-whitspace and function-order autofixes

### PR DESCRIPTION
**Pull request by gomesalexandre**
As the bot needs it, this is a WIP PR, it doesn't and shouldn't be merged now, not until future commits.

### CODE REVIEW

**Comment by duaraghav8** [comment]
@gomesalexandre are you still working on this?

**Comment by gomesalexandre** [comment]
@duaraghav8 Yes I am, I will finish the work on the rules I started working on during next week, not sure why the Gitcoin bot reopened this without posting a "Are you still working on this? If so, please make a WIP PR" style message

**Comment by gomesalexandre** [comment]
Closing as I have no ownership of this one anymore since long !

**Comment by duaraghav8** [comment]
Was this PR incomplete from your side or pending review from mine?
If pending review, I'll keep it opened and merge down the line.
If incomplete, please ignore.
Thanks

**Pull request closed without merging**
